### ISSUE TITLE
4th Kubernetes Study, 2022-06-28

### ISSUE THREAD

**Issue by jungkim0829** [wjrmffldrhrl/Kubernetes-Study#8]
https://meet.google.com/izw-ecwj-qng

레플리케이션과 그 밖의 컨트롤러: 관리되는 파드 배포

**Comment by jungkim0829** [comment]
1, 156.p yaml에 `kind: pod` -> `kind: Pod` 쿠버네티스는 리소스를 대문자로 시작해야 한다.

2, kubia-liveness-probe.yaml 
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: kubia-liveness
spec:
  containers:
  - image: luksa/kubia-unhealthy
    name: kubia
    livenessProbe:
    httpGet:
      path: /
      port: 8080
```
```
➜  chapter4 kubectl create -f kubia-liveness-probe.yaml 
error: error validating "kubia-liveness-probe.yaml": error validating data: ValidationError(Pod.spec.containers[0]): unknown field "httpGet" in io.k8s.api.core.v1.Container; if you choose to ignore these errors, turn validation off with --validate=false
```
책에서 `livenessProbe:` 에 들여쓰기해서 `httpGet:` 을 넣어야 됬는데 그냥 넣어서 필드를 못찼았네요;;


==


 kubia-liveness-probe.yaml 
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: kubia-liveness
spec:
  containers:
  - image: luksa/kubia-unhealthy
    name: kubia
    livenessProbe:
      httpGet:
        path: /
        port: 8080
```
